add wheels support
pdbpp/pdbpp pull request #72
Opened 2017-10-29 14:39 UTC by jairhenrique

2017-11-21 23:25 UTC, antocuni requested changes

2017-11-21 23:25 UTC, antocuni commented on pdbrc.py
> -import readline
this is exactly why I don't like/care about PEP8 linters: if I happen to uncommend the `readline.parse_and_bind` line below, the code will break because `readline` is not imported. Could you please remove this commit from the PR?

2017-11-21 23:27 UTC, antocuni commented
sorry for the late response. Apparently, I added a comment to the PR weeks ago, but I didn't submit the full review, so it was not visible to anyone else than me 😞

2017-11-21 23:40 UTC, blueyed commented on pdbrc.py
> -import readline
Maybe the import can be moved (and commented) to the example below then?

2017-11-21 23:54 UTC, jairhenrique commented on pdbrc.py
> -import readline
I like and do @blueyed suggestion.

2017-11-22 00:03 UTC, antocuni approved these changes

2017-11-22 00:03 UTC, merged